export const schema = `
CREATE TABLE IF NOT EXISTS Notes (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Title TEXT NOT NULL CHECK(length(trim(Title)) > 0),
  Content TEXT NOT NULL DEFAULT '',
  CreatedAt TEXT NOT NULL,
  UpdatedAt TEXT NOT NULL,
  IsCompleted INTEGER NOT NULL DEFAULT 0 CHECK(IsCompleted IN (0, 1))
);
CREATE TABLE IF NOT EXISTS Reminders (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  NoteId INTEGER NOT NULL UNIQUE REFERENCES Notes(Id) ON DELETE CASCADE,
  ReminderDateTime TEXT NOT NULL,
  IsActive INTEGER NOT NULL DEFAULT 1 CHECK(IsActive IN (0, 1)),
  CreatedAt TEXT NOT NULL
);
PRAGMA user_version = 1;
`;
